
# Use different management port as security rule
management:
    port: 8081
    security.enabled: false

# Enable shutdown
endpoints.shutdown.enabled: true

# Thrift server config
lmsiaAbcThriftServer:
  port: 3000
  name: lmsia-abc-thrift-server

# Eureka Config
eureka:
  instance:
    appname: ${lmsiaAbcThriftServer.name}
    nonSecurePort: ${lmsiaAbcThriftServer.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client.serviceUrl.defaultZone: http://eureka-server-test:8761/eureka/

# DB Config
lmsiaAbc.datasource:
  # For more see http://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html#Common_Attributes
  username: sbmvt
  password: hehehe 
  testOnBorrow: true
  validationQuery: SELECT 1
  url: jdbc:mysql://sbmvt-mysql-test:3306/lmsia-abc

# Profiles
spring:
  profiles.active: test,local
---
spring:
  profiles: local

# log config file
logging.config: classpath:logback.local.xml
---
spring:
  profiles: test

# log config file
logging.config: classpath:logback.test.xml

---
spring:
  profiles: online

# log config file
logging.config: classpath:logback.online.xml

# Eureka Config Online
eureka:
  client.serviceUrl.defaultZone: http://eureka-server-online:8761/eureka/

# DB Config Online
lmsiaAbc.datasource.url: jdbc:mysql://sbmvt-mysql-online:3306/lmsia-abc
