
# Use different management port as security rule
management:
    port: 8081
    security.enabled: false

# micro-service name
msName: lmsia-abc

# MySQL Default Datasource
spring.datasource:
  url: jdbc:mysql://192.168.99.100/lmsia_abc?rewriteBatchedStatements=true
  username: lmsia
  password: pass
  testOnBorrow: true
  validationQuery: SELECT 1
  tomcat:
    max-active: 500

# jpa related
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
spring.jpa.hibernate.ddl-auto: validate
spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# memcached
memcached.serverList: "192.168.99.100:11211"

# redis
redis.server: "192.168.99.100:6379"

# rocket mq
spring.rocketmq:
    nameServer: 127.0.0.1:9876
    producer.group: ${msName}

# Profiles
spring:
  profiles.active: test,local
---
spring:
  profiles: local

---
spring:
  profiles: test

---
spring:
  profiles: online

