
# Use different management port as security rule
management:
    port: 8081
    security.enabled: false

# Enable shutdown
endpoints.shutdown.enabled: true

# Thrift server config
lmsiaAbcThriftServer:
  port: 3000
  name: lmsia-abc-thrift-server

# Profiles
spring:
  profiles.active: test,local
---
spring:
  profiles: local

# log config file
logging.config: classpath:logback.local.xml
---
spring:
  profiles: test

# log config file
logging.config: classpath:logback.test.xml

---
spring:
  profiles: online

# log config file
logging.config: classpath:logback.online.xml

